#!/usr/bin/env python3
"""Generate combined canvas api-server http_route_manifest.rs."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

CRATES = [
    "sdkwork-routes-canvas-app-api",
    "sdkwork-routes-canvas-backend-api",
]

ROUTE_ENTRY = re.compile(
    r"HttpRoute::(\w+)\(\s*"
    r"HttpMethod::(\w+),\s*"
    r'"([^"]+)",\s*'
    r'"([^"]+)",\s*'
    r'"([^"]+)",\s*'
    r"\),",
    re.MULTILINE,
)


def extract_http_routes(manifest_path: Path) -> list[str]:
    text = manifest_path.read_text(encoding="utf-8")
    blocks: list[str] = []
    for auth, method, path, tag, op in ROUTE_ENTRY.findall(text):
        blocks.append(
            "\n".join(
                [
                    f"    HttpRoute::{auth}(",
                    f"        HttpMethod::{method},",
                    f'        "{path}",',
                    f'        "{tag}",',
                    f'        "{op}",',
                    "    ),",
                ]
            )
        )
    return blocks


def main() -> None:
    blocks: list[str] = []
    for crate in CRATES:
        manifest = ROOT / "crates" / crate / "src" / "http_route_manifest.rs"
        blocks.extend(extract_http_routes(manifest))

    if not blocks:
        raise SystemExit("no routes extracted for combined manifest")

    output = "\n".join(
        [
            "// @generated by tools/gen_canvas_combined_http_route_manifest.py — do not edit",
            "",
            "use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};",
            "",
            "const HTTP_ROUTES: &[HttpRoute] = &[",
            *blocks,
            "];",
            "",
            "pub fn canvas_route_manifest() -> HttpRouteManifest {",
            "    HttpRouteManifest::new(HTTP_ROUTES)",
            "}",
            "",
            "pub fn canvas_public_path_prefixes() -> Vec<String> {",
            '    vec!["/health".to_string(), "/healthz".to_string()]',
            "}",
            "",
        ]
    )

    out_path = ROOT / "crates" / "sdkwork-canvas-api-server" / "src" / "http_route_manifest.rs"
    out_path.write_text(output, encoding="utf-8")
    print(f"wrote {len(blocks)} routes to {out_path}")


if __name__ == "__main__":
    main()
